name: ci

on:
  push:
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-10.15, macos-11 ]
        rustc-channel: [ nightly, beta, stable ]

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rustc-channel }}
          default: true
          profile: default

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ matrix.platform }}-${{ matrix.rustc-channel }}-cargo-${{ hashFiles('**/src-tauri/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.platform }}-${{ matrix.rustc-channel }}-cargo-

      - name: Cargo Clippy
        run: cargo clippy --all-targets --all-features

      - name: Cargo Build
        run: cargo build --release --all

      - name: Cargo Test
        run: |
          cargo test --release --all
          cargo test --release --all-features
          cargo test --release --no-default-features

      - name: Cargo Doc
        run: cargo doc --release --no-deps --all
